export interface Animation {
  name: string;
  category: 'entrance' | 'exit' | 'attention' | 'special' | 'shadow';
  value: string;
  description: string;
  examples: string[];
  gradient: string;
  content?: string;
}

export const animations: Animation[] = [
  // ENTRANCE ANIMATIONS
  {
    name: 'Fade In',
    category: 'entrance',
    value: 'fadeIn',
    description: 'Gradually appear from transparent.',
    examples: ['fadeIn', 'fadeIn({ opacity: 0.5 })'],
    gradient: 'from-orange-400 to-teal-600',
  },
  {
    name: 'Slide In',
    category: 'entrance',
    value: 'slideIn({ y: "100%" })',
    description: 'Slide in with optional rotation.',
    examples: ["slideIn({ x: '-100%', opacity: 0, rotate: 0 })", "slideIn({ y: '100%' })"],
    gradient: 'from-amber-200 to-amber-400',
    content: '<div class="w-16 h-24 bg-amber-600 rounded-lg transform -rotate-12"></div>',
  },
  {
    name: 'Zoom In',
    category: 'entrance',
    value: 'zoomIn()',
    description: 'Zoom in with optional rotation.',
    examples: ['zoomIn', 'zoomIn({ x: 0, y: 0, scale: 0, opacity: 0, rotate: 0 })'],
    gradient: 'from-slate-100 to-slate-300',
    content: '<div class="w-32 h-32 rounded-full bg-gradient-to-r from-red-400 via-yellow-400 to-purple-400"></div>',
  },
  {
    name: 'Bounce In',
    category: 'entrance',
    value: 'bounceIn()',
    description: 'Bounce in with elastic effect.',
    examples: ['bounceIn', 'bounceIn({ scale: 0, opacity: 0 })'],
    gradient: 'from-blue-300 to-blue-500',
    content: '<div class="w-24 h-24 rounded-full bg-white"></div>',
  },
  {
    name: 'Flip In',
    category: 'entrance',
    value: 'flipIn',
    description: 'Flip in with customizable axis.',
    examples: ['flipIn', "flipIn({ axis: 'x', degrees: 90 })", "flipIn({ axis: 'y', degrees: 180 })"],
    gradient: 'from-green-300 to-yellow-500',
    content: '<div class="w-28 h-28 bg-green-700 rounded-lg"></div>',
  },
  {
    name: 'Rotate In',
    category: 'entrance',
    value: 'rotateIn',
    description: 'Rotate in with fade.',
    examples: ['rotateIn', 'rotateIn({ rotate: -180, opacity: 0 })'],
    gradient: 'from-red-400 to-red-600',
    content: '<div class="w-28 h-28 bg-red-800 rounded-xl transform rotate-45"></div>',
  },
  {
    name: 'Light Speed In',
    category: 'entrance',
    value: 'lightSpeedIn',
    description: 'Fast entrance with skew.',
    examples: ['lightSpeedIn', "lightSpeedIn({ distance: '-100%', skew1: -30, skew2: 20, skew3: 0, opacity: 0 })"],
    gradient: 'from-purple-300 to-purple-600',
  },
  {
    name: 'Roll In',
    category: 'entrance',
    value: 'rollIn',
    description: 'Roll in from the side.',
    examples: ['rollIn', "rollIn({ x: '-100%', rotate: -360, opacity: 0 })"],
    gradient: 'from-pink-300 to-pink-600',
    content: '<div class="w-24 h-24 rounded-full bg-pink-800"></div>',
  },
  {
    name: 'Big Entrance',
    category: 'entrance',
    value: 'bigEntrance',
    description: 'Dramatic spinning entrance.',
    examples: ['bigEntrance', 'bigEntrance({ scale: 0, rotate: 720, opacity: 0 })'],
    gradient: 'from-red-500 to-yellow-500',
  },
  {
    name: 'Hatch',
    category: 'entrance',
    value: 'hatch',
    description: 'Emerge with rotation.',
    examples: ['hatch', 'hatch({ scale: 0, rotate: -180, opacity: 0 })'],
    gradient: 'from-purple-400 to-pink-600',
    content: '<div class="w-24 h-32 bg-purple-800 rounded-full"></div>',
  },
  {
    name: 'Swing In',
    category: 'entrance',
    value: 'swingIn',
    description: 'Swing entrance with progressive rotation.',
    examples: ['swingIn', 'swingIn({ start: 15, mid1: -15, mid2: 5, end: 0 })'],
    gradient: 'from-teal-400 to-cyan-600',
  },
  {
    name: 'Back In',
    category: 'entrance',
    value: 'backIn',
    description: 'Back in with overshoot effect.',
    examples: ['backIn', 'backIn({ x: 0, y: 0, startScale: 0, midScale: 1.3, endScale: 1, opacity: 0 })'],
    gradient: 'from-sky-400 to-blue-600',
  },
  {
    name: 'Jack In The Box',
    category: 'entrance',
    value: 'jackInTheBox',
    description: 'Pops out with rotation.',
    examples: ['jackInTheBox', 'jackInTheBox({ scale: 0, rotate1: 45 })'],
    gradient: 'from-violet-400 to-purple-600',
  },
  // EXIT ANIMATIONS
  {
    name: 'Fade Out',
    category: 'exit',
    value: 'fadeOut',
    description: 'Gradually disappear to transparent.',
    examples: ['fadeOut', 'fadeOut({ opacity: 0.5 })'],
    gradient: 'from-slate-400 to-slate-600',
  },
  {
    name: 'Slide Out',
    category: 'exit',
    value: 'slideOut',
    description: 'Slide out in any direction.',
    examples: ["slideOut({ x: '100%' })", "slideOut({ x: '0', y: '-100%', opacity: 0 })"],
    gradient: 'from-gray-300 to-gray-500',
  },
  {
    name: 'Zoom Out',
    category: 'exit',
    value: 'zoomOut',
    description: 'Zoom out to smaller size.',
    examples: ['zoomOut', 'zoomOut({ scale: 0, opacity: 0 })'],
    gradient: 'from-zinc-300 to-zinc-600',
  },
  {
    name: 'Bounce Out',
    category: 'exit',
    value: 'bounceOut',
    description: 'Bounce out with elastic effect.',
    examples: ['bounceOut', 'bounceOut({ scale: 0, opacity: 0 })'],
    gradient: 'from-neutral-300 to-neutral-600',
  },
  {
    name: 'Flip Out',
    category: 'exit',
    value: 'flipOut',
    description: 'Flip out with customizable axis.',
    examples: ['flipOut', "flipOut({ axis: 'x', degrees: 90 })", "flipOut({ axis: 'y', degrees: -90 })"],
    gradient: 'from-stone-300 to-red-500',
  },
  {
    name: 'Rotate Out',
    category: 'exit',
    value: 'rotateOut',
    description: 'Rotate out with fade.',
    examples: ['rotateOut', 'rotateOut({ rotate: 180, opacity: 0 })'],
    gradient: 'from-orange-300 to-orange-500',
  },
  {
    name: 'Light Speed Out',
    category: 'exit',
    value: 'lightSpeedOut',
    description: 'Fast exit with skew.',
    examples: ['lightSpeedOut', "lightSpeedOut({ distance: '100%', skew: 30, opacity: 0 })"],
    gradient: 'from-amber-300 to-amber-500',
  },
  {
    name: 'Roll Out',
    category: 'exit',
    value: 'rollOut',
    description: 'Roll out to the side.',
    examples: ['rollOut', "rollOut({ x: '100%', rotate: 360, opacity: 0 })"],
    gradient: 'from-yellow-300 to-yellow-500',
  },
  {
    name: 'Back Out',
    category: 'exit',
    value: 'backOut',
    description: 'Back out with overshoot effect.',
    examples: ['backOut', 'backOut({ scale1: 1.2 })', 'backOut({ duration: 0.8 })'],
    gradient: 'from-lime-300 to-green-500',
  },
  // ATTENTION SEEKERS
  {
    name: 'Pulse',
    category: 'attention',
    value: 'pulse',
    description: 'Pulsing scale with optional fade.',
    examples: ['pulse', 'pulse({ scale1: 1.2 })', 'pulse({ opacity: 0 })'],
    gradient: 'from-pink-400 to-rose-600',
  },
  {
    name: 'Shake',
    category: 'attention',
    value: 'shake(  {timeline: {repeat: 10} })',
    description: 'Horizontal shake effect.',
    examples: ['shake', "shake({ x1: '-10px', x2: '10px' })"],
    gradient: 'from-red-400 to-orange-600',
  },
  {
    name: 'Jello',
    category: 'attention',
    value: 'jello',
    description: 'Jello-like wobble effect.',
    examples: ['jello', 'jello({ skewX1: -12.5, skewX2: 6.25, skewY1: -12.5, skewY2: 6.25 })'],
    gradient: 'from-green-400 to-emerald-600',
  },
  {
    name: 'Heart Beat',
    category: 'attention',
    value: 'heartBeat',
    description: 'Heart beating effect.',
    examples: ['heartBeat', 'heartBeat({ scale: 1.3 })'],
    gradient: 'from-red-400 to-pink-600',
    content: '<div class="text-6xl">❤️</div>',
  },
  {
    name: 'Flash',
    category: 'attention',
    value: 'flash',
    description: 'Flashing opacity effect.',
    examples: ['flash', 'flash({ opacity: 0 })'],
    gradient: 'from-yellow-300 to-yellow-500',
  },
  {
    name: 'Pull',
    category: 'attention',
    value: 'pull',
    description: 'Quick pull motion up or down.',
    examples: ['pull', "pull({ direction: 'down' })", "pull({ y: '30', direction: 'up' })"],
    gradient: 'from-red-400 to-orange-500',
  },
  {
    name: 'Float',
    category: 'attention',
    value: 'float',
    description: 'Gentle up and down movement.',
    examples: ['float', "float({ y1: '-30px', y2: '-15px' })", 'float({ duration: 2, repeat: -1 })'],
    gradient: 'from-sky-400 to-blue-500',
  },
  {
    name: 'Pop',
    category: 'attention',
    value: 'pop',
    description: 'Quick scale up with overshoot.',
    examples: ['pop', 'pop({ scale2: 1.3 })', 'pop({ duration: 0.3 })'],
    gradient: 'from-indigo-400 to-violet-500',
  },
  // SPECIAL EFFECTS
  {
    name: 'Spin',
    category: 'special',
    value: 'spin',
    description: 'Complete 360° rotation.',
    examples: ['spin', 'spin({ degrees: 720 })', 'spin({ degrees: -360 })'],
    gradient: 'from-purple-500 to-pink-500',
  },
  {
    name: 'Morphing',
    category: 'special',
    value: 'morphing',
    description: 'Shape transformation effect.',
    examples: ['morphing', 'morphing({ scale1: 1.5, rotate: 90 })'],
    gradient: 'from-violet-500 to-fuchsia-500',
  },
  {
    name: 'Skew',
    category: 'special',
    value: 'skew',
    description: 'Skew/tilt transformation.',
    examples: ['skew', 'skew({ skewX: -20, skewY: -20 })'],
    gradient: 'from-fuchsia-500 to-pink-500',
  },
  {
    name: 'Expand',
    category: 'special',
    value: 'expand',
    description: 'Scale up on both axes.',
    examples: [
      'expand({ scaleX: 1.5, scaleY: 1.5 })',
      'expand({ scaleX: 2, scaleY: 1 })',
      'expand({ scaleX: 1.2, scaleY: 1.2, duration: 2 })',
    ],
    gradient: 'from-red-500 to-orange-500',
  },
  {
    name: 'Blur',
    category: 'special',
    value: 'blur',
    description: 'Blur to focus effect.',
    examples: ['blur', "blur({ blur1: '10px', blur2: '0px', opacity: 0 })"],
    gradient: 'from-cyan-400 to-blue-600',
  },
  // SHADOW EFFECTS
  {
    name: 'Glow',
    category: 'shadow',
    value: 'glow',
    description: 'Glow effect animation.',
    examples: ['glow', "glow({ boxShadow: '0 0 20px rgba(255, 255, 255, 0.8)' })"],
    gradient: 'from-amber-400 to-yellow-500',
  },
];
