export interface Animation {
  name: string;
  category: 'entrance' | 'exit' | 'attention' | 'special' | 'shadow' | 'text';
  value: string;
  description: string;
  examples: string[];
  gradient: string;
  content?: string;
}

export const animations: Animation[] = [
  // ENTRANCE ANIMATIONS
  {
    name: 'Fade In',
    category: 'entrance',
    value: 'fadeIn',
    description: 'Gradually appear from transparent.',
    examples: ['fadeIn', 'fadeIn({ opacity: 0.5 })'],
    gradient: 'from-orange-400 to-teal-600',
  },
  {
    name: 'Slide In',
    category: 'entrance',
    value: 'slideIn({ axis: "y", distance: -200 })',
    description: 'Slide in from a specified direction.',
    examples: ['slideIn', "slideIn({ axis: 'x', distance: '100%' })", "slideIn({ axis: 'y', distance: '100%' })"],
    gradient: 'from-amber-200 to-amber-400',
    content: '<div class="w-16 h-24 bg-amber-600 rounded-lg transform -rotate-12"></div>',
  },
  {
    name: 'Zoom In',
    category: 'entrance',
    value: 'zoomIn()',
    description: 'Zoom in from small to normal size with fade.',
    examples: ['zoomIn', "zoomIn({ x: '0', y: '100%' })", 'zoomIn({ scale: 0.1 })'],
    gradient: 'from-slate-100 to-slate-300',
    content: '<div class="w-32 h-32 rounded-full bg-gradient-to-r from-red-400 via-yellow-400 to-purple-400"></div>',
  },
  {
    name: 'Bounce In',
    category: 'entrance',
    value: 'bounceIn()',
    description: 'Bounce in with elastic scaling effect.',
    examples: ['bounceIn', 'bounceIn({ scale: 0.1 })', "bounceIn({ x: '100%' })"],
    gradient: 'from-blue-300 to-blue-500',
    content: '<div class="w-24 h-24 rounded-full bg-white"></div>',
  },
  {
    name: 'Flip In',
    category: 'entrance',
    value: 'flipIn',
    description: 'Flip in with customizable axis.',
    examples: ['flipIn', "flipIn({ axis: 'y' })"],
    gradient: 'from-green-300 to-yellow-500',
    content: '<div class="w-28 h-28 bg-green-700 rounded-lg"></div>',
  },
  {
    name: 'Rotate In',
    category: 'entrance',
    value: 'rotateIn',
    description: 'Rotate in with fade.',
    examples: ['rotateIn', "rotateIn({ rotate: '-360deg' })", "rotateIn({ rotate: '180deg' })"],
    gradient: 'from-red-400 to-red-600',
    content: '<div class="w-28 h-28 bg-red-800 rounded-xl transform rotate-45"></div>',
  },
  {
    name: 'Light Speed In',
    category: 'entrance',
    value: 'lightSpeedIn',
    description: 'Fast entrance with skew effect.',
    examples: ['lightSpeedIn', "lightSpeedIn({ distance: '-100%' })"],
    gradient: 'from-purple-300 to-purple-600',
  },
  {
    name: 'Roll In',
    category: 'entrance',
    value: 'rollIn',
    description: 'Roll in from the side.',
    examples: ['rollIn', "rollIn({ distance: '100%', degrees: 120 })"],
    gradient: 'from-pink-300 to-pink-600',
    content: '<div class="w-24 h-24 rounded-full bg-pink-800"></div>',
  },
  {
    name: 'Big Entrance',
    category: 'entrance',
    value: 'bigEntrance',
    description: 'Dramatic spinning entrance.',
    examples: ['bigEntrance', 'bigEntrance({ scale: 0, rotate: 720, opacity: 0 })'],
    gradient: 'from-red-500 to-yellow-500',
  },
  {
    name: 'Hatch',
    category: 'entrance',
    value: 'hatch',
    description: 'Emerge with rotation.',
    examples: ['hatch', 'hatch({ scale: 0, rotate: -180, opacity: 0 })'],
    gradient: 'from-purple-400 to-pink-600',
    content: '<div class="w-24 h-32 bg-purple-800 rounded-full"></div>',
  },
  {
    name: 'Swing In',
    category: 'entrance',
    value: 'swingIn',
    description: 'Swing entrance with progressive rotation.',
    examples: ['swingIn', 'swingIn({ startRotate: 20, midRotate1: -15 })'],
    gradient: 'from-teal-400 to-cyan-600',
  },
  {
    name: 'Back In',
    category: 'entrance',
    value: 'backIn',
    description: 'Back in from position with scale and fade.',
    examples: ['backIn', "backIn({ y: '-100%', x: '0' })", 'backIn({ scale: 0.5, opacity: 0 })'],
    gradient: 'from-sky-400 to-blue-600',
  },
  {
    name: 'Jack In The Box',
    category: 'entrance',
    value: 'jackInTheBox',
    description: 'Pops out with rotation.',
    examples: ['jackInTheBox', 'jackInTheBox({ scale: 0, startRotate: 45 })'],
    gradient: 'from-violet-400 to-purple-600',
  },
  // EXIT ANIMATIONS
  {
    name: 'Fade Out',
    category: 'exit',
    value: 'fadeOut',
    description: 'Gradually disappear to transparent.',
    examples: ['fadeOut', 'fadeOut({ opacity: 0.5 })'],
    gradient: 'from-slate-400 to-slate-600',
  },
  {
    name: 'Slide Out',
    category: 'exit',
    value: 'slideOut({ axis: "x", distance: "200%" })',
    description: 'Slide out in any direction.',
    examples: ["slideOut({ axis: 'x', distance: '100%' })", "slideOut({ axis: 'y', distance: '-100%' })"],
    gradient: 'from-gray-300 to-gray-500',
  },
  {
    name: 'Zoom Out',
    category: 'exit',
    value: 'zoomOut',
    description: 'Zoom out to smaller size with fade.',
    examples: ['zoomOut', "zoomOut({ x: '100%', y: '0' })", 'zoomOut({ scale: 0.3 })'],
    gradient: 'from-zinc-300 to-zinc-600',
  },
  {
    name: 'Bounce Out',
    category: 'exit',
    value: 'bounceOut',
    description: 'Bounce out with elastic effect.',
    examples: ['bounceOut', "bounceOut({ x: '100%' })", "bounceOut({ y: '100%' })"],
    gradient: 'from-neutral-300 to-neutral-600',
  },
  {
    name: 'Flip Out',
    category: 'exit',
    value: 'flipOut',
    description: 'Flip out with customizable axis.',
    examples: ['flipOut', "flipOut({ axis: 'y' })"],
    gradient: 'from-stone-300 to-red-500',
  },
  {
    name: 'Rotate Out',
    category: 'exit',
    value: 'rotateOut',
    description: 'Rotate out with fade.',
    examples: ['rotateOut', "rotateOut({ rotate: '360deg' })", "rotateOut({ rotate: '180deg', y: '1000' })"],
    gradient: 'from-orange-300 to-orange-500',
  },
  {
    name: 'Light Speed Out',
    category: 'exit',
    value: 'lightSpeedOut',
    description: 'Fast exit with skew effect.',
    examples: ['lightSpeedOut', "lightSpeedOut({ distance: '-100%' })"],
    gradient: 'from-amber-300 to-amber-500',
  },
  {
    name: 'Roll Out',
    category: 'exit',
    value: 'rollOut',
    description: 'Roll out to the side.',
    examples: ['rollOut', "rollOut({ distance: '-100%', degrees: -120 })"],
    gradient: 'from-yellow-300 to-yellow-500',
  },
  {
    name: 'Back Out',
    category: 'exit',
    value: 'backOut',
    description: 'Back out to position with scale and fade.',
    examples: ['backOut', "backOut({ x: '0', y: '1000' })", 'backOut({ scale: 0.5, opacity: 0.5 })'],
    gradient: 'from-lime-300 to-green-500',
  },
  // ATTENTION SEEKERS
  {
    name: 'Pulse',
    category: 'attention',
    value: 'pulse',
    description: 'Pulsing scale effect.',
    examples: ['pulse', 'pulse({ scale1: 1.1 })'],
    gradient: 'from-pink-400 to-rose-600',
  },
  {
    name: 'Shake',
    category: 'attention',
    value: 'shake({ timeline: { repeat: 10 } })',
    description: 'Shake effect on X or Y axis.',
    examples: ['shake', "shake({ axis: 'y' })", 'shake({ distance: 15 })'],
    gradient: 'from-red-400 to-orange-600',
  },
  {
    name: 'Jello',
    category: 'attention',
    value: 'jello',
    description: 'Jello-like wobble effect.',
    examples: ['jello', 'jello({ skewX: -20, skewY: -20 })'],
    gradient: 'from-green-400 to-emerald-600',
  },
  {
    name: 'Heart Beat',
    category: 'attention',
    value: 'heartBeat',
    description: 'Heart beating effect.',
    examples: ['heartBeat', 'heartBeat({ scale: 1.3 })'],
    gradient: 'from-red-400 to-pink-600',
    content: '<div class="text-6xl">❤️</div>',
  },
  {
    name: 'Flash',
    category: 'attention',
    value: 'flash',
    description: 'Flashing opacity effect.',
    examples: ['flash', 'flash({ opacity: 0 })'],
    gradient: 'from-yellow-300 to-yellow-500',
  },
  {
    name: 'Pull',
    category: 'attention',
    value: 'pull',
    description: 'Quick pull motion up or down.',
    examples: ['pull', "pull({ direction: 'down' })", "pull({ y: '30', direction: 'up' })"],
    gradient: 'from-red-400 to-orange-500',
  },
  {
    name: 'Float',
    category: 'attention',
    value: 'float',
    description: 'Gentle up and down movement.',
    examples: ['float', "float({ startY: '-30', endY: '-15' })"],
    gradient: 'from-sky-400 to-blue-500',
  },
  {
    name: 'Pop',
    category: 'attention',
    value: 'pop',
    description: 'Quick scale up with overshoot.',
    examples: ['pop', 'pop({ midScale: 1.3 })'],
    gradient: 'from-indigo-400 to-violet-500',
  },
  // SPECIAL EFFECTS
  {
    name: 'Spin',
    category: 'special',
    value: 'spin',
    description: 'Complete 360° rotation.',
    examples: ['spin', 'spin({ degrees: 720 })', 'spin({ degrees: -360 })'],
    gradient: 'from-purple-500 to-pink-500',
  },
  {
    name: 'Morphing',
    category: 'special',
    value: 'morphing',
    description: 'Shape transformation effect.',
    examples: ['morphing', 'morphing({ startScale: 1.5, rotate: 90 })'],
    gradient: 'from-violet-500 to-fuchsia-500',
  },
  {
    name: 'Skew',
    category: 'special',
    value: 'skew',
    description: 'Skew/tilt transformation.',
    examples: ['skew', 'skew({ skewX: -20, skewY: -20 })'],
    gradient: 'from-fuchsia-500 to-pink-500',
  },
  {
    name: 'Expand',
    category: 'special',
    value: 'expand',
    description: 'Scale up on both axes simultaneously.',
    examples: ['expand', 'expand({ scaleX: 1.5, scaleY: 1.5 })', 'expand({ scaleX: 2, scaleY: 1 })'],
    gradient: 'from-red-500 to-orange-500',
  },
  {
    name: 'Blur',
    category: 'special',
    value: 'blur',
    description: 'Blur to focus transition.',
    examples: ['blur', 'blur({ startBlur: 20 })', 'blur({ endBlur: 5 })', 'blur({ duration: 2 })'],
    gradient: 'from-cyan-400 to-blue-600',
  },
  // SHADOW EFFECTS
  {
    name: 'Glow',
    category: 'shadow',
    value: 'glow',
    description: 'Glow effect animation.',
    examples: ['glow', "glow({ boxShadow: '0 0 20px rgba(255, 255, 255, 0.8)' })"],
    gradient: 'from-amber-400 to-yellow-500',
  },
  // TEXT ANIMATIONS
  {
    name: 'Screen Reader',
    category: 'text',
    value: 'screenReader',
    description: 'Words fade in sequentially with stagger effect.',
    examples: ['screenReader', 'screenReader({ stagger: 0.2 })', 'screenReader({ opacity: 0.5, stagger: 0.05 })'],
    gradient: 'from-indigo-400 to-purple-600',
    content:
      '<div>"Life is a sequence of moments, each one different but unique. Each moment is a small part of the whole, and together they form a beautiful and intricate tapestry that is the fabric of our lives."</div>',
  },
  {
    name: 'Slide Reveal',
    category: 'text',
    value: 'slideReveal({ axis: "x", distance: "150" })',
    description: 'Characters slide in with fade and stagger from any direction.',
    examples: [
      'slideReveal({ axis: "x", distance: "150" })',
      'slideReveal({ axis: "x", distance: "-150" })',
      'slideReveal({ axis: "y", distance: "150" })',
    ],
    gradient: 'from-cyan-400 to-blue-600',
    content: '<div>"Each letter glides into view, painting words across the canvas of imagination."</div>',
  },
  {
    name: 'Word Drop',
    category: 'text',
    value: 'wordDrop',
    description: 'Words fall from above with random rotation and bounce effect.',
    examples: ['wordDrop', 'wordDrop({ y: -150, stagger: 0.2 })', 'wordDrop({ rotation: "[-45,45]", ease: "bounce" })'],
    gradient: 'from-violet-400 to-purple-600',
    content:
      '<div>"Words tumble down like autumn leaves, each one dancing to its own rhythm before settling into place."</div>',
  },
  {
    name: 'Text Flip',
    category: 'text',
    value: 'textFlip({ selector: ".animation-content" })',
    description: 'Text elements flip in with 3D perspective and rotation effect. Supports lines, words, or characters.',
    examples: [
      'textFlip',
      'textFlip({ rotationX: -120, stagger: 0.3 })',
      'textFlip({ target: "chars", stagger: 0.05 })',
      'textFlip({ target: "words", transformOrigin: "50% 50% -200px" })',
    ],
    gradient: 'from-pink-400 to-rose-600',
    content:
      '<div>"Each element unfolds like a page turning in space, revealing its message with dramatic flair and depth."</div>',
  },
];
